# Generated by Django 3.2.8 on 2021-12-05 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('piso', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_condominio', to='api.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, max_digits=9)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=9)),
                ('numero_operacion', models.CharField(max_length=30)),
                ('vencimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_departamento', to='api.departamento')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_propietario', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_servicio', to='api.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('departamentos', models.PositiveSmallIntegerField(default=0)),
                ('pisos', models.PositiveSmallIntegerField(default=0)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificio_condominio', to='api.condominio')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_edificio', to='api.edificio'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='propietarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
