# Generated by Django 3.2.8 on 2021-12-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('departamentos', models.PositiveSmallIntegerField(default=0)),
                ('pisos', models.PositiveSmallIntegerField(default=0)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condminios', to='api.condominio')),
            ],
        ),
    ]
